### ISSUE TITLE
Add loading prop to Relays readyState..?

### ISSUE THREAD

**Issue by zth** [relay-tools/relay-query-lookup-renderer#19]
Sorry, this isn't an actual issue, but rather a question;

I'd like to be able to distinguish when the `QueryRenderer` is loading data (making requests) in order handle intermediate loading states (primarily when changing query variables which causes a new network request). I have a PR ready for this complete with tests, which adds a `loading` boolean to `readyState` in `QueryRenderer`. But, before submitting the pull request - is this something you'd be willing to discuss merging? I understand it diverges from the original thought of this repo. 

Otherwise I'll just fork and use that for my specific use case, but maybe this could benefit others too.

**Comment by robrichard** [comment]
When you change query variables, `readyState` gets reset to the default (`{props: null}`) when the new request begins. Wouldn't `!props && !error` reliably tell you when data is loading?

**Comment by zth** [comment]
Yeah, it would I guess. Thanks for the clarification!
