### ISSUE TITLE
Breaks in React Native

### ISSUE THREAD

**Issue by SatyaFariz** [relay-tools/relay-query-lookup-renderer#22]
This library works fine with react relay app on the web but it breaks with react native relay

**Comment by robrichard** [comment]
Can you provide more details? Any error messages? Which version of this package are you using and which versions of relay and react native?

**Comment by SatyaFariz** [comment]
Turns out it breaks only if i provide the lookup props. If i don't it works just fine

react: 16.6.0-alpha.8af6728
react-native: 0.57.4
react-relay: 1.7.0
relay: 0.8.0-1
relay-query-lookup-renderer: 3.0.2

![screenshot_2019-02-05-00-16-59-007_com tuan_rumah_mobile](https://user-images.githubusercontent.com/25284201/52225702-9be6fa00-28dd-11e9-8d47-7b353a8bfb59.png)

**Comment by robrichard** [comment]
I don't have a React Native environment that I can debug with and I don't really understand what is not working from the stack trace. Can you open a PR with a fix for this issue? Can you also please ensure this is still an issue with the latest version of Relay (2.0.0) and this package (4.0.0)?

**Comment by zth** [comment]
For anyone else stumbling on this, I encountered the same thing (plus another weird issue where `relay-query-lookup-renderer` was simply `undefined`) and for me it had nothing to do with this package, it was simply a case of React Native handling require cycles differently in later versions. Require cycles = circular dependencies, example: module A depends on module B which depends on module A. This sometimes causes modules not to be instantiated properly on boot, and there's not always a clear path in the error message to the require cycle that's actually causing the breakage.

So, for me, solving this + the additional weird issue I had was a matter of going through and fixing all the require cycles in my app (the console tells you which they are) so this and all other modules could be instantiated properly.

**Comment by SatyaFariz** [comment]
Fixed it after upgrading to React 16.8.6 and RN 0.59.4
