### ISSUE TITLE
Does not behave same as QueryRenderer - Does multiple fetch requests

### ISSUE THREAD

**Issue by ro-savage** [relay-tools/relay-query-lookup-renderer#26]
@robrichard 

The react-relay query render will performance once fetch, regardless of how many times it appears in the react tree.

For example
```
import {QueryRenderer} from 'react-relay';
const something = [1,2,3]
{something.map( () => <QueryRenderer {...props} /> )
```

Will cause a single request.

```
import {QueryLookupRenderer} from 'relay-query-lookup-renderer';
const something = [1,2,3]
{something.map( () => <QueryLookupRenderer {...props} /> )
```

Will fire 3 requests, if it can not find the data in the store.

Only difference between these two screenshots was using switch `QueryRenderer` for `QueryLookupRenderer`
![image](https://user-images.githubusercontent.com/9244507/79629983-c26f1900-81a1-11ea-9cfd-89f191fdc2fa.png)

![image](https://user-images.githubusercontent.com/9244507/79629992-d87cd980-81a1-11ea-87e8-9843a87d0107.png)

**Comment by robrichard** [comment]
@ro-savage this was forked from Relay's QueryRenderer before they introduced a query cache. I don't plan to make any updates to this package. It will be deprecated in favor of the `store-or-network` fetch policy currently in Relay experimental.

**Comment by ro-savage** [comment]
Thanks for the info Rob.
